### ISSUE TITLE
line numbers are wrong when using \ line continuation within string literals

### ISSUE THREAD

**Issue by dorssel** [etas/vs-boost-unit-test-adapter#100]
Any discovered Boost test *after* a line continuation *within* a string literal is off by the number of in-string-line-continuations used.

char *s = "Hello, \
world!"

/// test discovery has a line number off-by-one
BOOST_AUTO_TEST_CASE(some_test)

**Comment by netspiri** [comment]
Hi @dorssel,

Thank you for your interest in the project. Will look into this when we have the time.

**Comment by guwirth** [comment]
@dorssel should be also solved with new approach.  Please do some testing with #109
