### ISSUE TITLE
Unit Tests executed one by one when using Analyze Code Coverage->All tests

### ISSUE THREAD

**Issue by gastart** [etas/vs-boost-unit-test-adapter#101]
Using:
 VS 2015 with Update 1
 BUTA v1.0.7.77

When selecting **Analyze code Coverage** and then selecting **All Tests**, the tests seems to be executing one by one in different execution instances.  The expected implementation was that the tests would be run in one execution instance, for more time efficiency and increased productivity.

**Comment by netspiri** [comment]
Might be related to this: http://stackoverflow.com/questions/35163843/vstestcode-coverage-broken-after-sp1-for-visual-studio-2015-installed

**Comment by guwirth** [comment]
We observed similar problem. Selecting **All Tests** and running tests from command line with `run_test=*` should result in the same test execution sequence. Otherwise it's sometimes difficult to find out why automation is failing.

**Comment by netspiri** [comment]
Started debugging this issue and it seems that the Visual Studio APIs are not signalling us that data collection is enabled.

The test executor assumes that the `IRunContext.IsDataCollectionEnabled` flag is raised when choosing some form of code coverage. When the executor notes this, then we automatically switch to `source` test batching (1 execution per test module/exe). Unfortunately, when using Visual Studio 2015 update 1, this flag is set to false. Not knowing, at that point we have to assume the worst and fall back to the `test` test batching mechanism (1 execution per test)

To be honest, I have no clue on how to proceed. Tried updating the registry as noted in the link but it had no effect.

**Comment by guwirth** [comment]
@netspiri Maybe you should ask in a Microsoft forum if this is an known issue? Other possibility could be to test with Update 2. Maybe this is already fixed?

**Comment by netspiri** [comment]
Issue does not seem to be fixed with Update 2. Any hints on where to report this?

**Comment by guwirth** [comment]
Micosoft has a Visual Studio 2015 UserVoice site. This site is for suggestions and ideas for the IDE of Visual Studio (Community, Professional or Enterprise). You can also add suggestions for [Team Services](https://visualstudio.uservoice.com/forums/330519-team-services) or [Visual Studio Code](https://visualstudio.uservoice.com/forums/293070-visual-studio-code). Or go to [Connect](https://connect.microsoft.com/visualstudio) to file a bug.

**Comment by netspiri** [comment]
Filed a report to Visual Studio using the [Report a Problem](https://msdn.microsoft.com/en-us/library/mt632287.aspx) feature.

**Comment by netspiri** [comment]
Tried this out on Visual Studio 2015 Update 3 Enterprise again using the latest debug build available on appveyor and it seems that the issue has been fixed: all tests within the module are executed in one go when Test - Analyze Code Coverage - All Tests is selected.

**Comment by guwirth** [comment]
fixed with "Visual Studio 2015 Update 3"
