### ISSUE TITLE
Support Boost utf::disabled() and uft::enable_if<condition> decorators

### ISSUE THREAD

**Issue by maschwie** [etas/vs-boost-unit-test-adapter#110]
Please support the boost decorators (for test suite and test case):
- utf::disabled() 
- and utf::enabled(), when it overrides a disabled suite - see "decorator_05" example in the docu
- utf::enable_if<CompileTimeConstant>()
I.e. visualize the "disabled" status in the VS Test explorer for test cases disabled by this decorators. 

Should be relatively easy to realize by my guess as the "--list_content" content command differs between disabled and non-disabled test cases

http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/tests_organization/enabling.html
http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/utf_reference/test_org_reference/decorator_enable_if.html

See docu: 
> decorator_06 --list_content
test_io*
test_db

**Comment by guwirth** [comment]
@maschwie my first feeling: static tests are possible to support (enable/disable). Test conditions evaluated during runtime not:  enable_if.

**Comment by maschwie** [comment]
"template <bool Condition> enable_if()" should work too
the decorator only supports **compile time constants** and its status is already covered by "--list_content" according to the examples in the boost manual

**Comment by netspiri** [comment]
Enabled status can be identified also via `--list_content=DOT` and can be noted to users via a trait, similar to how we identify test suites. This would still list a disabled test and users would still have the ability to execute said tests, just like one can do in the command line.

Unfortunately, and more important, there has been a slight change in `--list_content=DOT` between Boost 1.59 and Boost 1.60. Running `--list_content=DOT` in Boost 1.59 will list all test cases as disabled (`color=yellow`) whereas in Boost 1.60 this has been fixed (`color=green`) and is now inline with `--list_content=(HRF)`. We need to handle this with care unless we want all Boost 1.59 users to see all tests as disabled.

**Comment by maschwie** [comment]
> We need to handle this with care unless we want all Boost 1.59 users to see all tests as disabled.
What about providing a config option and disabling the feature as "default" value ?

The "disable" decorator (similar to the NUnit "Ignore" Attribute) is really a nice feature to temporary disable tests and far better than alternatives line "uncomment" or add "skip code" that sometimes later are not  removed by accident.

**Comment by maschwie** [comment]
Note:
http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/utf_reference/test_org_reference/decorator_precondition.html

Only this decorator supports dynamic conditions evaluated at run-time and cannot be checked via "--list_content" supporting this decorator would be a different issue / story.

**Comment by guwirth** [comment]
@maschwie our current idea is to remove the source code parsing and relay completely on the provided `--list_content=DOT` results. 

@netspiri 

> Enabled status can be identified also via --list_content=DOT and can be noted to users via a trait, similar to how we identify test suites. This would still list a disabled test and users would still have the ability to execute said tests, just like one can do in the command line.

Ok we should implement this.

> Unfortunately, and more important, there has been a slight change in --list_content=DOT between Boost 1.59 and Boost 1.60. Running --list_content=DOT in Boost 1.59 will list all test cases as disabled 

Is there a possibility to find out which boost version we are using (maybe a version number in the DOT file)? Think this can always be the case in future that they are changing there DOT file format a little bit and we have to support it. If there is no version number in the DOT file we should ask the boost test developers to add one to have at least in future a possibility to find out the file format.

We are still using 1.59 version so at least we need still support for this version.

**Comment by netspiri** [comment]
Unfortunately, no version information is encoded within the DOT representation.

Also tried out the Nunit Ignore option and what we noted is that tests which have the `Ignore` attribute specified are marked with the test skipped icon upon execution. We should be able to mirror said behaviour but again, this will cause an issue for Boost 1.59 users since at that point, all tests will not be able to execute since all will be marked as skipped.

**Comment by guwirth** [comment]
@netspiri should be possible now after supporting only boost 1.60+.
