### ISSUE TITLE
Test is not failed when exception in separate thread is thrown

### ISSUE THREAD

**Issue by ngjermundshaug** [etas/vs-boost-unit-test-adapter#111]
Example test:

    BOOST_AUTO_TEST_CASE(ExceptionTest)
    {
    	new boost::thread([]{
    		throw "Error";
    	});
    
    	while (true)
    	{
    		boost::this_thread::sleep_for(boost::chrono::milliseconds(1000));
    	}
    }

Test is neither green nor red - it failed to execute properly. Should be marked as failed.

![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/d6508763-8fd7-49fe-8dd4-36838cd72526/2016-03-21_1021.png)

![](http://content.screencast.com/users/ngjhaug/folders/Jing/media/0c60f464-4ada-4ead-aba6-3ab1a5c92773/2016-03-21_1019.png)

    ------ Run test started ------
    Logger initialized. Logging to C:\USERS\XXXXXXXX\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\12.0\EXTENSIONS\QI54KFEU.GYY\BoostTestAdapter.dll.log
    Executing:   -> [ExceptionTest]
    Exception caught while running test batch C:\XXXXX\Output\XXXXTest.exe [ExceptionTest] (Root element is missing.)
    ========== Run test finished: 0 run (0:00:02.1212487) ==========

**Comment by netspiri** [comment]
Hi @ngjermundshaug and many thanks for your feedback.

Running the provided test case with a recent build shows the following:

![notfoundorisempty](https://cloud.githubusercontent.com/assets/6962427/13914805/1ec78fb2-ef51-11e5-8d3d-3cc63f3d6080.png)

This has been introduced in PR #106.

**Comment by ngjermundshaug** [comment]
Nice. Are the test builds publicly available anywhere?

Do you know when a new version containing this fix will be released?

**Comment by netspiri** [comment]
Builds of the master branch are available from [AppVeyor](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master). Build badge from the project's front page on GitHub should also link to the latest master build.

[![Build status](https://ci.appveyor.com/api/projects/status/28lw0jb0k19ekmtq/branch/master?svg=true)](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master)

Regarding a public release, I would refer to @guwirth for more information.

**Comment by ngjermundshaug** [comment]
Tried with the latest build - works great!

![](http://i.giphy.com/qHho9D3nk3nS8.gif)
