### ISSUE TITLE
Update Documentation/Wiki

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#112]
Update documentation based on recent activity. Most notably being:

|Issue/PR|Description|
|-----------|---------------|
|#49|Parallel Test Execution/Discovery|
|#98|Working Directory|
|#99|Environment Variables|
|#107|Standard Output/Error Configuration|
|#108|Test Inclusion/Exclusion Configuration|
|#109|`--list_content` Support|

**Comment by netspiri** [comment]
Documentation updated on our fork: https://github.com/netspiri/vs-boost-unit-test-adapter/wiki

**Comment by guwirth** [comment]
:+1:
