### ISSUE TITLE
"Failing Tests in case Memory Leaks are Detected" is not working

### ISSUE THREAD

**Issue by SimonLux** [etas/vs-boost-unit-test-adapter#114]
I configured a .runsettings file to detect memory leaks through failing tests:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<BoostTest>
        <FailTestOnMemoryLeak>true</FailTestOnMemoryLeak>
	</BoostTest>
</RunSettings>
```
Unfortunately, tests with memory leaks do not fail. Example test:
```
BOOST_AUTO_TEST_CASE(TestMalloc)
{
    malloc(42);
}

```
Test Result:
> Test Name:	TestMalloc
> Test Outcome:	**Passed**
> Result StandardOutput:	results_collector.ipp(203): message in "TestMalloc": Test case FindXCPSlaves/TestMalloc did not check any assertions
> Result StandardError:	Detected memory leaks!
> Dumping objects ->
> {3503} normal block at 0x005A5670, 42 bytes long.
>  Data: <                > CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD CD 
> Object dump complete.

I can reproduce this behaviour with the released v1.0.6.20 and the latest v1.0.7.36 of the Boost Unit Test Adapter.

**Comment by netspiri** [comment]
Hi @SimonLux,

Took a quick glance at the issue and it seems to stem from the fact that memory leak information is now being redirected to standard error rather than standard output. Currently we only monitor standard output for said reports.

Will be tackling this issue eventually when we have time.

**Comment by guwirth** [comment]
Hi @netspiri,

> memory leak information is now being redirected to standard error

What means 'now'? Starting with which boost or VS version?

Regards,
Günter

**Comment by netspiri** [comment]
Now means: boostorg/test@fb390a3eb68c8a14b54982e88ecab4425b7df629. I believe this was introduced in Boost 1.59.
