### ISSUE TITLE
VS2015 Update 2 - Test Case Visualisation Problems

### ISSUE THREAD

**Issue by maschwie** [etas/vs-boost-unit-test-adapter#115]
It looks like tests are executed correctly, but the icons update is bugged.
See Screen shot attached.

**Comment by maschwie** [comment]
Ok - file upload does not work from company network.
Text description:
TestCase List (e.g. Project): Shows "!" for TextCaseXYZ
Detailed view below the list shows: "TestCaseXYZ" ... Test Successful

**Comment by netspiri** [comment]
Could not reproduce mentioned error on a test Visual Studio 2015 Community Edition v14.0.25123.00 Update 2 installation using test adapter v1.0.7.36.

Tested both regular and parallel test execution, 'Run All' and 'Run Selected Tests'. No anomalies were noticed.

![virtualbox_windows8_20_04_2016_08_47_05](https://cloud.githubusercontent.com/assets/6962427/14665620/a84b7506-06d4-11e6-94f5-e561aef83489.png)

![virtualbox_windows8_20_04_2016_08_45_30](https://cloud.githubusercontent.com/assets/6962427/14665616/a53ec9ee-06d4-11e6-990e-60623c498963.png)

**Comment by guwirth** [comment]
@maschwie not reproducible. Can we close this?

**Comment by maschwie** [comment]
ok close - i suppose we will try again to switch with VS 2015 to the newest boost adapter version in the next days / weeks and see :-)
