### ISSUE TITLE
Conditionals filter error with BOOST_VERSION

### ISSUE THREAD

**Issue by Flamefire** [etas/vs-boost-unit-test-adapter#118]
As there is a minor issue with different boost versions and `BOOST_GLOBAL_FIXTURE` we needed to add a check like this:

    #if BOOST_VERSION >= 105900
        BOOST_GLOBAL_FIXTURE(TestSetup);
    #else
	    // Boost < 1.59 got the semicolon inside the macro causing an "extra ;" warning
	    BOOST_GLOBAL_FIXTURE(TestSetup)
    #endif

However this makes the parser throw this error:
> The conditionals filter encountered error: Unable to evaluate expression "BOOST_VERSION >= 105900" whilst processing line number 58 of source file "C:\Users\Alex\Documents\s25client\src\test\main.cpp". The source file will not be filtered for conditionals

At least the boost version check should work IMO

**Comment by netspiri** [comment]
Hi @Flamefire,

We are currently trying to move away from parsing source code directly and will be focusing on making use of `--list_contet=DOT` output. We can add a dummy value to the macro just to get things running. What I would recommend is to try the current (in-development v1.0.7) version (available via the appveyor badge). This makes use of a new discovery technique which should, hopefully, address your issue.

[![Build status](https://ci.appveyor.com/api/projects/status/28lw0jb0k19ekmtq/branch/master?svg=true)](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master)
