### ISSUE TITLE
Boost test project from template always has the same GUID

### ISSUE THREAD

**Issue by hoensr** [etas/vs-boost-unit-test-adapter#119]
Currently, if I create a new Boost test project from the template provided here, it always has the same GUID:

    <ProjectGuid>{82125DA1-1CD7-45B5-9281-E6AE7C287CB7}</ProjectGuid>

If I create several test projects, they might be mixed up. 

Therefore it would be better to always create a new GUID. This can probably be done with a placeholder

    <ProjectGuid>$guid1$</ProjectGuid>

as [described here](https://reasoncodeexample.com/2013/06/09/creating-visual-studio-project-templates/).

**Comment by netspiri** [comment]
Hi @hoensr,

Many thanks for your interest in the project and for the link related project template parameters. Will definitely implement your suggestions in the future.
