### ISSUE TITLE
Installation fail if .NET Framework 4.6 is installed

### ISSUE THREAD

**Issue by clevesque2** [etas/vs-boost-unit-test-adapter#127]
When trying to install the extension on a computer with .NET Framework 4.6, the installation fail with the following message:
Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'Boost Unit Test Adapter' requires a version of the .NET Framework that is not installed.

The problem is in the .vsixmanifest file which requires .NET 4.5 instead of .NET 4.5 or higher. 
I changed Version="4.5"  to Version="[4.5,)" and it fixes the problem.

**Comment by guwirth** [comment]
@clevesque2 thanks for your feedback we will change it.
