### ISSUE TITLE
Forward additional options to test-runner via .runsettings

### ISSUE THREAD

**Issue by megaposer** [etas/vs-boost-unit-test-adapter#13]
Copied over from original request on the VS extension site:

It would be nice if debug code assertions could coexist with the Boost UTF when running the tests from the Test Explorer in VS. Our code is interspersed with a lot of FOO_ASSERT macros which, basically call _ASSERTE if _DEBUG is defined, otherwise evaluates to ((void)0). Nothing fancy.

So basically something like ...

    FOO_ASSERT(nullptr != ptr);
    if(nullptr == ptr) throw std::invalid_argument(...);

Within the unit test I want to catch the "invalid_argument" exception, but because of the FOO_ASSERT, the Boost UTF catches a system error.

On command line this can be circumvented with "--catch_system_errors=no". Using the Boost Unit Tet Adapter via the Test Explorer, one cannot pass the required parameter though (.runsettings does not support it) and using it as environment variable "BOOST_TEST_CATCH_SYSTEM_ERRORS=no" somehow failed.

So, it would be great to have a way to add this to the config options. Or would there be another/better way to achieve this? I don't want to recompile the debug code just because of unit testing.

Thanks!

**Comment by netspiri** [comment]
Hello @megaposer. Your requirement has been understood. Currently we do not support it....and no easy workaround comes to mind so as to somehow easily inject the command.

If you so badly need it I would suggest you to modify BoostTestRunnerCommandLineArgs.ToString() and build a version for yourself.  Additionally you can work your way back so to load the settings from the runsettings file via class BoostTestAdapterSettings.  If you want to debug, add a breakpoint at both of the overloaded function BoostTestExecutor.RunTests()

We are planning to do a small sprint so as to implement the regex fix that another user mentioned in another issue and maybe the inclusion of some options such as yours.

**Comment by guwirth** [comment]
Question is which options do exist to realize this? Would prefer a solution with a macro. Is it not possible to set something like BOOST_TEST_CATCH_SYSTEM_ERRORS=no in the code?

**Comment by megaposer** [comment]
I already tried to set `BOOST_TEST_CATCH_SYSTEM_ERRORS=no` as en environment variable via a (DEBUG only) property sheet, i.e. define it as a macro and then mark it to be exported as an environment variable.

This failed, the environment setting is not picked up by the Boost UTF.

This would have been my preferred solution as well because then I could cater for `assert` and friends  causing system errors in DEBUG builds only.

Hence my original request to extend the .runsettings file/parsing with the appropriate _catch_system_errors_ setting and forward it to the test-runner. 

I was encouraged to submit this issue as a more generic request to forward (arbitrary) commands to the test runner after raising the problem on the Visual Studio extension site.

**Comment by guwirth** [comment]
For my understanding it would be the best to be able to define this per project (exe) and not global for all. With a ```BOOST_TEST_CATCH_SYSTEM_ERRORS=no``` I mean there should be a macro in the source code to turn this on/off. Don't know if this this possible?

**Comment by megaposer** [comment]
I agree, the definition per project would be preferable.

I checked the code in Boost 1.58.0 (probably the same applies to 1.59.0).  

    boost_1_58_0\boost\test\impl\cpp_main.ipp(72): boost::unit_test::const_string p( std::getenv( "BOOST_TEST_CATCH_SYSTEM_ERRORS" ) );

This is the only occurrence I could find where the environment variable is handled, so there is no _MACRO_ processing. The Boost UTF either ignores catching system errors when _--catch_system_errors=no_ is given as a command line argument to the test runner or when the Boost UTF execution monitor finds the environment variable to be `BOOST_TEST_CATCH_SYSTEM_ERRORS != no` ...

To reiterate the original issue:

Disabling this setting when running from the command line or running the test suite via "debug" within Visual Studio is _NOT_ a problem. It is only problematic when using the Test Explorer within VS in conjunction with the Unit Test Adapter to _run_ tests.

In that case, I assume, the Unit Test Adapter invokes the Boost UTF test runner itself and passes parameters defined within _.runsettings_ accordingly.

But even if I set the aforementioned environment variable as part of the project, it  has no effect whatsoever.

If one uses the Test Explorer in VS to _debug_ tests, it seems the `BOOST_TEST_CATCH_SYSTEM_ERRORS` setting gets disabled as the execution is monitored separately and the test runner is started somehow "differently".

**Comment by netspiri** [comment]
Hi @megaposer,

Your request has been implemented and a new ``<CatchSystemErrors>`` configuration element has been added to the .runsettings configuration. Should you need to disable it, simply set:

``<CatchSystemErrors>false</CatchSystemErrors>``

in the ``<BoostTest>`` configuration section.

Since this feature has just been merged, it should be available in the next release of the adapter. 

@guwirth: Can this issue be closed?

**Comment by guwirth** [comment]
Hi @megaposer are you able build and verify the solution? If not we will close the issues and you can reopen it if there are still problems in the next release.

**Comment by megaposer** [comment]
Hi @guwirth ,

sorry for the late response. I was out of the office for a while. Thanks so much for adding the option, I will try it out ASAP.

Cheers
