### ISSUE TITLE
Omit build before executing tests

### ISSUE THREAD

**Issue by laufhannes** [etas/vs-boost-unit-test-adapter#134]
Is there a way to omit the build before executing the tests?

The respective project consists of a dozen modules, all with their own solutions for e.g. the model and the unit tests. Trying to run a single unit test suite results in a global build - probably because the current build fails, but it's only a single module that fails and is not my business currently.

Waiting for the build and accepting *There were build errors. Would you like to continue and run tests from the last successful build?* does work, but it'd be a timesaver to just skip this build via some action/checkbox/configuration.

**Comment by netspiri** [comment]
Unfortunately, I do not think that we have the capabilities to address this from the adapter side. The adapter simply tries to discover and execute tests from modules which were compiled. I think this behaviour is inherent to Visual Studio.

May I suggest to unload the project temporarily. This should alleviate some of your troubles.

**Comment by netspiri** [comment]
Hi @laufhannes,

Are there any updates regarding this issue? Did unloading the project help?

**Comment by laufhannes** [comment]
Yes, it does - but that's only a temporary solution. I thought that running unit tests is a simple console command but it seems that it's not that simple in this case and then there's probably nothing to do about.
