### ISSUE TITLE
Possibility to link directly to failing test line

### ISSUE THREAD

**Issue by alarobric** [etas/vs-boost-unit-test-adapter#138]
Currently the test output will link to test cases, but I'd like to be able to link directly to the offending line. By running my tests as a post-build step I can currently get failing test lines to appear in my Errors list and link from there to the line.

I've never used the Test Explorer much before, but is this something that could be possible or not?

**Comment by guwirth** [comment]
Hi @alarobric, thanks for your interest.
* the usage of the TestExplorer is described here: https://msdn.microsoft.com/library/hh270865.aspx
* and [Find the Test Case Location in Source](https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#find-the-test-case-location-in-source)

Hope this helps.
Regards,

**Comment by netspiri** [comment]
Hi @alarobric and thanks for your interest in the project.

Currently the adapter does not link directly to the error, it just lists the location of the error. Unfortunately, we cannot interact with the error list but there is a similar interface where we list errors in the test explorer window. 

We have looked at other adapters and it seems that it might be possible to emulate your request via the stack-trace feature of the adapter where the first error can be listed in a hyper-link-able stack-trace. Will update this issue as we progress further in this regard.

**Comment by guwirth** [comment]
@alarobric maybe you can try with #144 and give us feedback.
