### ISSUE TITLE
Supported versions in Visual Studio Gallery

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#15]
Looking in the Visual Studio Gallery the versions below are shown as supported. For VS2015 there is only *Professional* listed? Should be also the other versions?

```
 Supported versions:

    Visual Studio 2015
    Visual Studio 2013
    Visual Studio 2012

Supported Visual Studio 2012 Editions:

    Visual Studio 2012 Professional
    Visual Studio 2012 Premium
    Visual Studio 2012 Ultimate

Supported Visual Studio 2013 Editions:

    Visual Studio 2013 Professional
    Visual Studio 2013 Premium
    Visual Studio 2013 Ultimate

Supported Visual Studio 2015 Editions:

    Visual Studio 2015 Professional
```

**Comment by gastart** [comment]
Hello @guwirth. Which section to the Visual Studio Gallery are you referring to?  Are you maybe referring to the [pre-requisites](https://github.com/etas/vs-boost-unit-test-adapter#pre-requisites) section?

**Comment by guwirth** [comment]
This is from the upload dialog on the Visual Studio Gallery page. After uploading the installer I see the info above. Creating the installer is there a possibility to define the supported VS versions? Wondering why the information is different for 2012, 2013 and 2015.

**Comment by gastart** [comment]
Ok. I understand.  With the installer currently available on the Visual Studio Gallery BUTA can be installed without problems in also both the enterprise version and the community edition.

My guess is that the portal is making use of the manifest file in the installer.  We will try to update the manifest so that it makes the portal happy.

**Comment by guwirth** [comment]
Seems to be a problem of https://github.com/etas/vs-boost-unit-test-adapter/blob/2ec6fd6b99c3b2b23afec4872bd898a9f56b8593/BoostTestPlugin/source.extension.vsixmanifest. Maybe the InstallationTarget IDs of VS2015 are different?

**Comment by gastart** [comment]
Hello @guwirth. Pull request #25 should solve the issue.
