### ISSUE TITLE
Update Visual Studio Gallery Description

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#154]
As mentioned in the Visual Studio Gallery 'Q & A' section, the description as stated in the gallery is out of date, especially in the area regarding DLL test execution. The description should ideally be updated to reflect the current feature set of the project.

**Comment by guwirth** [comment]
@netspiri could you make a proposal please. Will update the Visual Studio Gallery then.

**Comment by netspiri** [comment]
Boost Test Adapter is available as an extension for Microsoft Visual Studio. It makes use of the Unit Test Explorer (UTE) provided by Microsoft to visualize and run unit test cases that are written using open source Boost Test Library.

Refer to ﻿﻿﻿http://www.boost.org/doc/libs/release/libs/test for detailed information on the Boost Test Library.

__Pre-Requisites__
- Microsoft Visual Studio 2015
- Boost Libraries v1.60 or greater

__Supported Functionality__
- List all test cases
- Execute all or select test cases
- Convenient display of test output and details
- Easy location of test cases and errors within code base
- Search for test cases by specific criteria
- Group tests by test suite, status and labels
- Execute DLL test modules by making use of external test runners
- And more as listed in https://github.com/etas/vs-boost-unit-test-adapter/wiki

__Version History__
- https://github.com/etas/vs-boost-unit-test-adapter/releases

The Boost Test Adapter is an open source project. We are grateful for any contributions and support. https://github.com/etas/vs-boost-unit-test-adapter

**Comment by guwirth** [comment]
It's replaced with text above. For 1.0.7 pre-requisites are different.
