### ISSUE TITLE
Better memory leak detection support

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#156]
Like to have better support for memory leak detection. Should be possible to jump to location of memory leak after running a test.

Idea is to have new menu point: 'Detect Memory Leak'; run the test in debug mode and stop at the (first) memory leak position.

Maybe it is a two step process? First get leak allocation numbers and then jump to one (first) of this numbers.

> [detect_memory_leaks](http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/detect_memory_leaks.html): ... positive value tells the framework to detect the memory leaks (if any). Any value greater then 1 in addition is treated as leak allocation number and setup runtime breakpoint. In other words setting this parameter to the positive value N greater than 1 causes the framework to set a breakpoint at Nth memory allocation (don't do that from the command line - only when you are under debugger). Note: if your test program produce memory leaks notifications, they are combined with allocation number values you could use to set a breakpoint. Currently only applies to MS family of compilers ...

**Comment by guwirth** [comment]
> Memory leak detection can only occur when executing a test. Memory leak reports only provide the allocation number (and not the source code line number) so it is not possible to provide the ability to jump to source code lines after execution.

That's why I wrote it is a two step process.
* First running single unit test with `detect_memory_leaks=1` to get the memory leak report with the allocation numbers and
* second step is then to run unit test in debug mode with `detect_memory_leaks=allocation number` to stop at the erroneous code location.

> It is possible to expose this command line argument as a configuration attribute but I do not think this is very convenient. Modifying the .runsettings file, reloading, and re-running is not a very intuitive process when compared to modifying the command line arguments in the project's 'Debug' property sheet.

That's the reason I like to have something inbuild which is doing this all automatically.

> Regarding the use of additional menus, it is not possible to do so within the test adapter framework. It is possible to create an additional Visual Studio extension packaged with the test adapter and somehow synchronize the data between the two but this is not trivial and will require some thought and time in order to do it correctly.

If other plugins can call the 'additional menu' API why not also this plugin (as part of the installation)?

**Comment by guwirth** [comment]
> If other plugins can call the 'additional menu' API why not also this plugin (as part of the installation)?

Or other idea could be to have the memory leak report as list like https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual#find-the-test-case-location-in-source and selection of one allocation number starts adapter again with  `detect_memory_leaks=allocation number`?

**Comment by wnewbery** [comment]
Could something automated be done using the Diagnostic Tools in VS2015 with the heap snapshot feature (ideally such that the snapshot comparison wont include Boost.Test related allocations, unlike my manual example with a global fixture below)?

I've found it pretty useful recently for manually locating memory issues (both plain leaks, and the infinitely growing container/collection kind) and it already has a lot of useful UI rather than trying to make something new.

![image](https://cloud.githubusercontent.com/assets/6324094/18187809/b35c3824-70a4-11e6-9d62-d1aa46f3a315.png)
![image](https://cloud.githubusercontent.com/assets/6324094/18187813/b71ce0f8-70a4-11e6-8dc2-e75f84f84837.png)

**Comment by guwirth** [comment]
@wnewbery idea sounds good but not clear for me how to realize it concrete? I understood;
* tool can provide comparison of memory usage: means there must be a snapshot before and after running an unit test?
* there must be a filter for boost parts?

**Comment by wnewbery** [comment]
@guwirth Unfortunately I am not particularly familiar with either the API's you have available to interact with the IDE (although I do hope MS provided something to signal points of interest for the CPU, Memory and GPU tools), or with Boost.Test internals to be sure exactly how such a thing would be achieved.

The basic idea would be to make VS take snapshots at points you are sure should have no net-allocations in between (any such remaining allocation being a leak). Maybe the start and end of the process lifetime (I assume this is where Boost's leak report comes from, maybe there is a call to [_CrtDumpMemoryLeaks](https://msdn.microsoft.com/en-us/library/x98tx3cf.aspx?f=255&MSPPError=-2147217396) at the very end before it exits?).
