### ISSUE TITLE
Only the first of multiple test labels is displayed in test explorer 

### ISSUE THREAD

**Issue by gastart** [etas/vs-boost-unit-test-adapter#160]
I would like to define multiple labels to a test as such

``` c++
BOOST_TEST_DECORATOR(* boost::unit_test::label("LABELA,LABELB") * boost::unit_test::label("LABELA") * boost::unit_test::label("LABELB") * boost::unit_test::label("LABELA LABELB"));
BOOST_AUTO_TEST_CASE(MyTest)
{
}
```

If I do execute --list_content=DOT all the labels are listed for the respective test but in the traits view of test explorer I do see only the first label.  All the others are missing.

**Comment by guwirth** [comment]
@gastart Is this a bug or an enhancement? Sounds more like a bug?

**Comment by gastart** [comment]
I labelled it as enhancement because I was not sure if was a use case that was already being catered for.

Later on, on Friday I looked at the code and the DOT file seems to be parsed correctly (there is also a unit test for this). I will now check what we are providing back to Visual Studio.

**Comment by gastart** [comment]
Sry closed the issue by mistake....and I have therefore reopened it.
