### ISSUE TITLE
Test discovery does not work for modules which have `#` in their path

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#167]
Test modules whose path contains the `#` symbol in their output directory path are not listed in the test adapter. By implication, tests cannot be executed for said modules.

Issue is present in the latest development version of the Boost Unit Test Adapter and Visual Studio 2015 Update 2.

**Comment by netspiri** [comment]
After digging into this, we noted that Visual Studio does not inform us of executables which are located within paths containing the `#` symbol. Unfortunately, this is handled by a layer above the test adapter API and we cannot do much about this because this is out of our control. This does not only affect the Boost Unit Test Adapter but also other test adapter implementations (e.g. Nunit test adapter).

This issue is also present in Visual Studio Update 3.

In order to remedy this, temporarily set the output directory of the module to a path which does not contain `#` symbols.

@guwirth How should we proceed regarding this?

**Comment by guwirth** [comment]
Hi @netspiri please create a VS issue and document the problem in our FAQ.

**Comment by netspiri** [comment]
Filed a report to Visual Studio using the [Report a Problem](https://msdn.microsoft.com/en-us/library/mt632287.aspx) feature.

**Comment by guwirth** [comment]
@netspiri issue also documented in our FAQ? If yes I will close this.

**Comment by netspiri** [comment]
FAQ updated as requested.
