### ISSUE TITLE
Q: when will be the next release?

### ISSUE THREAD

**Issue by candychiu** [etas/vs-boost-unit-test-adapter#171]
When will be the next release on NuGet?  Thanks.

**Comment by guwirth** [comment]
@candychiu if everything is working with boost 1.63 then after release of boost 1.63.

**Comment by guwirth** [comment]
@raffienficiaud maybe you have an idea?

**Comment by netspiri** [comment]
Update: Soon

**Comment by netspiri** [comment]
Boost Unit Test Adapter v1.0.8.44 is up on the Visual Studio Gallery.

Many thanks for the contributors and users which allowed for this release!
