### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#172]
Test the adapter to ensure that it works as expected in the newest versions of Visual Studio.

Hint(s):
- Make use of the available infrastructure by creating a DLL project `VisualStudio2017Adapter` to utilize the same mechanisms used in earlier test adapter versions.

**Comment by guwirth** [comment]
@netspiri Not sure if we should do this with next release? Think we should first focus on Boost 1.63 release? VS2017 is still a RC.

**Comment by raffienficiaud** [comment]
For 2017, there are some pending issues that would certainly affect the compilation of Boost.Test. Right now, I would say this is not working on our side (2017 apparently removed some C++11/C++14 deprecated features completely) .

**Comment by sergegers** [comment]
@raffienficiaud _HAS_AUTO_PTR_ETC key was removed completely?

**Comment by netspiri** [comment]
Visual Studio 2017 has been released. We should test with the latest version to ensure that the adapter can:
1) Compile successfully against Visual Studio 2017 libraries
2) The VSIX package can be installed for Visual Studio 2017 targets
2) Tests are discoverable and executable (even though these may be compiled using MSVC++ 14 compiler)
3) Interaction with Visual Studio (e.g. reading the `Environment` property from the Debugging property sheet) works as expected

**Comment by guwirth** [comment]
@netspiri yes makes sense to start now.

**Comment by sergegers** [comment]
So, how the porting at the new studio is going?

**Comment by netspiri** [comment]
Hi @sergegers,

Currently busy with other tasks at the moment so this had to be put on the back burner for a little while.

**Comment by raffienficiaud** [comment]
@netspiri Apparently Boost.Test seems to work fine with VS2017.

**Comment by FeBrex** [comment]
Are you aware that Microsoft is working on a Boost.Test adapter?

[https://blogs.msdn.microsoft.com/vcblog/2017/05/10/unit-testing-and-the-future-announcing-the-test-adapter-for-google-test/](https://blogs.msdn.microsoft.com/vcblog/2017/05/10/unit-testing-and-the-future-announcing-the-test-adapter-for-google-test/)

**Comment by guwirth** [comment]
@FeBrex I'm aware of this.

I was in contact with Microsoft and we agreed to the points below:
* Microsoft will fork our code base and will create and publish a Boost.Test solution.
* Microsoft committed to continuing the open source nature of this project.
* The Microsoft extension will be only compatible with Visual Studio 2017. They do not plan to add support for earlier versions of Visual Studio.
* We will continue working on the VS2015 solution but will no longer publish an own VS2017 solution.
* As long the Microsoft solution fits our needs we will contribute to the Microsoft solution instead of maintaining an own solution.

**Comment by cedral** [comment]
You wouldn't happen to know where the MS fork is would you? We need this because we are migrating from 2013 to 2017 and our solution uses it. Maybe MS is too slow and you should support it through 2017?

**Comment by netspiri** [comment]
Hi @cedral 

Thanks for the interest and support for the project.

I cannot answer your question regarding the MS fork - best to ask @guwirth about that.

If you need a stop-gap solution, we had started working on this on our fork (https://github.com/netspiri/vs-boost-unit-test-adapter/tree/vs2017 | https://ci.appveyor.com/project/netspiri/vs-boost-unit-test-adapter/build/1.0.9.218) but bear in mind that this is highly experimental. Read it as it does not fully work as intended because we found issues connecting to the Visual Studio instance to retrieve properties such as environment variables and working directory but test listing and execution does work. Once we heard of the fork, we ceased development on this so it is 1) not inline with master and 2) it is now rather old.

If you intend to try this, please proceed with extreme caution and remember to uninstall this version before attempting to use the one from the gallery since the experimental version will block automatic updates.

**Comment by emilm** [comment]
Is there a binary release for 2017? I am in a situation where I might need to install 2015 to support boost tests. Thanks!

**Comment by guwirth** [comment]
@all: There will be soon a version for Visual Studio 2017 from Microsoft - stay tuned.

**Comment by sergegers** [comment]
@guwirth Will it a separate component or a part of the Visual Studio? And do you know something about new VC++ issue date?

**Comment by guwirth** [comment]
@sergegers it will be a new plugin you can download from the Visual Studio Gallery. On the long run they are thinking about to integrate it into the default VS installation. Sources stay open source on an new GitHub repository. Microsoft will be in the lead to maintain this new repository.

**Comment by mwu-tow** [comment]
The new version of plugin has been published by Microsoft — see VC++ blog entry: https://blogs.msdn.microsoft.com/vcblog/2017/08/04/c-unit-testing-updates-announcing-boost-test-adapter-and-improved-google-test-support/

I'd like to use this occasion to thank ETAS team. Boost Unit Test Adapter became an indispensable tool for my daily work. Thank you for creating the extension and sharing it with the community!

**Comment by cedral** [comment]
I again reiterate that I wish you hadn't abandoned this. We standardized on it years ago and It is causing us real problems that we still can't use any of our existing tests 6 months after 2017 was released. 
The one from MS listed above doesn't work. I installed it from the marketplace and it is listed as installed but there is no new project template added to Visual C++ -> Test so I don't know what it means to say that it is installed.

**Comment by LukaszMendakiewicz** [comment]
@cedral I am one of the maintainers of the Microsoft fork. Please feel free to report any issues you may be having at our repo https://github.com/Microsoft/vs-boost-unit-test-adapter and we will want to make sure it works for you. It is indeed the case that project templates are not available in the version that we have released. Adding them back is something we have on our backlog, but with no specific timeframe. However if you create your own Boost.Test project from scratch, or import one created in Visual Studio 2015, the other functionality of the adapter - primarily listing, running, debugging tests in the Test Explorer should work.

**Comment by guwirth** [comment]
Hello @cedral,

as stated in #209 the 2017 MS version is a fork of this extension. Everything is as before except that MS is in the lead now.

The initial step is to install the extension, build your Boost.Test application and open the Test Explorer in VS. You should be able to see the boost tests now. We are using VS2015 & VS2017 with the test adapters without the need of any changes on our code base.

The project / item template is missing at the moment in the 2017 version.  But I think it's not a big issue to copy/paste one of your existing projects or create an own command line application and add the boost headers. 

Please have also a look to the wiki https://github.com/etas/vs-boost-unit-test-adapter/wiki/User-Manual. 

Best Regards,
