### ISSUE TITLE
Boost Unit Test Adapter Sample Configuration in wiki contains character sequences that are not allowed in XML comments and might prevent users from executing test properly

### ISSUE THREAD

**Issue by foobar303** [etas/vs-boost-unit-test-adapter#178]
When using a _.runsettings_ file created by simply copying and pasting from your wiki page https://github.com/etas/vs-boost-unit-test-adapter/wiki/Configuration executing tests in Viusal Studio fails due to an error with the following message: "Failed to load RunSettings file: 'c:\path\to\test.runsettings'. Please check if the file exists and is valid." This error is caused by using '--' (twice) within XML comments, which is not allowed. See _Character sequence '--' is not allowed in an XML comment_ https://msdn.microsoft.com/en-us/library/bb531321(v=vs.140).aspx for more information.

**Comment by gastart** [comment]
Hello @foobar303 Thanks for eyeing this one out. Many thanks. I'll take care of fixing it.

**Comment by gastart** [comment]
Removed the offending double hyphen from the xml comments in wiki commit 03438bc.

**Comment by guwirth** [comment]
@netspiri please fix for 1.0.8

**Comment by netspiri** [comment]
@guwirth Already addressed by @gastart

**Comment by gastart** [comment]
fixed documentation so we can close off this ticket.
