### ISSUE TITLE
Create new C++ Boost.Test repository for Test Adapter

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#183]
Create a new repository which consists of sample Boost.Test use cases for the Boost Unit Test Adapter. The core goal is to create a set of tests which will define the 'Acceptance Criteria' for future Boost Unit Test Adapter releases.

Hint(s):
- Consider making use of the examples available in the [Boost.Test](https://github.com/boostorg/test) GitHub repository.
- Tests should not consider solely general use, but also use cases which cover the use of '.runsettings' configuration, varying boost versions etc.

Bonus:
- Consider automating testing through the use of scripts and `vstest.console.exe` (if possible).

**Comment by guwirth** [comment]
@netspiri think would be better to contribute directly to the **Boost.Test repository** and add some command line tests there. This ensures a stable interface **before** they release a new version. Doing it here we will run typically into the problem that our feedback comes too late.

**Comment by guwirth** [comment]
@netspiri think is a good idea but would do it no more here in this repository. Let's do it in the Microsoft repository for VS2017.
