### ISSUE TITLE
Failure to detect tests if test EXE depends on unavailable DLLs

### ISSUE THREAD

**Issue by lordvalumart** [etas/vs-boost-unit-test-adapter#187]
If I create a Boost Test EXE which depends on some DLLs, but those DLLs are not available on the PATH, then the adapter fails to detect the tests in the EXE. Furthermore, no error is displayed, neither in the output window nor in the log.

It seems to me that this must be a very common situation, so it would be nice if the adapter handled it more elegantly. An entry on the "Troubleshooting" page in the wiki would also be useful (I can't find a way to edit the page myself).

**Comment by guwirth** [comment]
@lordvalumart I removed 'Restrict editing to users in teams with push access only '. So wiki is editable by all now.

**Comment by netspiri** [comment]
[FAQ](https://github.com/etas/vs-boost-unit-test-adapter/wiki/faq) section updated.

**Comment by guwirth** [comment]
@lordvalumart please try with latest snapshot and give us feedback: https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master/job/r38ciyccaavav66a/artifacts

**Comment by lordvalumart** [comment]
@guwirth The patch you suggested fixes the problem. I have also clarified the wording in the FAQ and added a corresponding section to the "troubleshooting" page in the wiki.

Thanks for the prompt help!
