### ISSUE TITLE
Test not flagged as failed whenever exceptions are caught whilst running a test

### ISSUE THREAD

**Issue by gastart** [etas/vs-boost-unit-test-adapter#190]
There are situations where for example a failure occurs when opening the log files (such as the one reported in #176),

```
Executing: -> [mytest01]
Exception caught while running test batch \Bin\Debug\Win32\i386\bin\BoostTest01.exe [mytest01] (The process cannot access the file 'C:\Users\gastart\AppData\Local\Temp\BoostTest01.exe.7096.6.test.stdout.log' because it is being used by another process.)

```
 it seems that we are not providing any test result back to visual studio and the test remains faded  out. A user might not notice that the test actually failed to "properly execute" and might think that everything went ok.

I would suggest that in case there is some exception in BUTA we do either declare the test as failed or as undetermined (the yellow triangle).

**Comment by guwirth** [comment]
@gastart yes should be fixed.

Not sure if should be marked as failed or undetermined? undetermined would have the advantage of be able to distinguish between defined and undefined failed?
