### ISSUE TITLE
Suppress Blocking Assertion Message Boxes

### ISSUE THREAD

**Issue by sergegers** [etas/vs-boost-unit-test-adapter#194]
During executing command "Run All" and other batch commands if the assertion message is triggered, it blocks the further execution. Is it possible to redirect these message to the log output? (I assume CrtReport mode is need to be changed https://msdn.microsoft.com/en-us/library/1y71x448.aspx )

**Comment by netspiri** [comment]
Hi @sergegers and thanks for the feedback. 

I think this may be related to issue #13 and the use of [`catch_system_errors`](http://www.boost.org/doc/libs/1_63_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/catch_system.html) option. Pull request #18 should have addressed this via a test adapter [configuration](https://github.com/etas/vs-boost-unit-test-adapter/wiki/Configuration) option.

Many thanks for `CrtReport` reference but alas, as test executors, we are in no position to modify the test code prior to execution, we simply execute the final build product. This solution, although feasible, requires the client/test adapter user to manually intervene and add this programmatic feature manually.

Boost.Test documentation does recommend that [managed/automated tools set this to `yes`](http://www.boost.org/doc/libs/1_63_0/libs/test/doc/html/boost_test/practical_usage_recommendations/command_line_usage_recommendatio.html#boost_test.practical_usage_recommendations.command_line_usage_recommendatio.if_you_got_fatal_exception_somew) so we should give this more thought and consider if it is worthwhile to default this option to `yes` for test adapter execution.

**Comment by sergegers** [comment]
@netspiri  I try to add command line argument --catch_system_error=yes to test project command line arguments and run it from IDE, but the assertion dialog is appeared again. Can you suppress it with this option?
My test case is:

`BOOST_AUTO_TEST_CASE(test)
{
    _ASSERTE(false);
}
`

VS 2015 U3, boost 1.63

**Comment by netspiri** [comment]
I tested the following:

```c++
BOOST_AUTO_TEST_CASE(test)
{
    _ASSERTE(false);
}
```

from the command line using `--catch_system_errors=yes` and `--catch_system_errors=no` and the default arguments with Boost 1.61 and Boost 1.63 with Visual Studio 2015 Update 2.

When launching the application using _Start (F5)_, regardless of the `catch_system_errors` value, Visual Studio will still cause the assert dialog to trigger. When launching the application using _Start Without Debugging (Ctrl+F5)_, the assert dialog does not show when `--catch_system_errors=yes` is used.

Moving back to the test adapter, I think a viable option is to set the `catch_system_errors` value to `yes` when the test is simply executed and such assertion errors are to be reported as test errors. When the test is debugged, we should opt for the current behaviour and expect assert dialog  boxes to pop up to aid debugging.

**Comment by sergegers** [comment]
@netspiri It will be great.
