### ISSUE TITLE
Test Runner in TFS 2015

### ISSUE THREAD

**Issue by kanekotic** [etas/vs-boost-unit-test-adapter#20]
How can I run the unit tests using the test runner under TFS 2015?

**Comment by netspiri** [comment]
Hi @kanekotic.

The post http://blogs.msdn.com/b/visualstudioalm/archive/2012/12/06/publishing-test-results-through-command-line-test-runner.aspx details how to integrate Visual Studio's test adapter infrastructure with TFS.

Unfortunately, as stated in the documentation, the current version of the Boost Test Adapter cannot be executed via command-line through vstest.console. If #24 is resolved, it could be the case that this may be possible in the future so please watch this space.

**Comment by kanekotic** [comment]
merci :)

**Comment by gastart** [comment]
Yes please, it would be appreciated.  Just out of curiosity, why are you saying that it is not that great? At the end of day the xml files generated by executable of the Boost Unit Test Framework should contain all the info you need.  What functionality are you missing...or what part of it is being messy?

**Comment by netspiri** [comment]
Issue _may_ be solved with PR #109
