### ISSUE TITLE
Performance Concerns For Test Discovery

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#204]
The adapter tends to perform slowly when discovering tests from a CMake generated solution which contains around 200 projects in total, of which approximately 50 of them are Boost.Test modules.

Investigate the performance of the driver in an attempt to improve the situation is possible.

**Comment by guwirth** [comment]
Think this is the same issue as #207. Think this "CMake issue" means:
* many big projects
* many unit tests per project

(nothing to do with CMake)

**Comment by netspiri** [comment]
Closing as being duplicated as of #207.
