### ISSUE TITLE
VS2015  Update 3 doesnt show information after tests execution

### ISSUE THREAD

**Issue by Mikhail2017** [etas/vs-boost-unit-test-adapter#215]
With boost 1.62.0.
Tests icons are gray and doesnt changes.
Updating to boost 1.65.1 makes it impossible to detect tests in Test Explorer.
Have tested in clean solution with autogenerated test project.

**Comment by netspiri** [comment]
Hi @Mikhail2017 and thanks for the feedback.

There is a known issue related to Boost 1.62 which is listed in the [FAQ](https://github.com/etas/vs-boost-unit-test-adapter/wiki/Frequently-Asked-Questions) section of our wiki. Instructions on how to use Boost.Test available in Boost 1.62 with the test adapter are available in there. (Hint: the following [.runsettings](https://github.com/etas/vs-boost-unit-test-adapter/wiki/resources/runsettings/sample-boost-162-workaround.runsettings) file should do the trick)

Regarding Boost 1.65, support for this version is still in the current development build and not available in the version available from Visual Studio gallery. Should you wish to try out the development build, it is available from [AppVeyor](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master). Please bear in mind that this is an in-production development build so proceed with caution and should you need to revert back to the original, simply uninstall the extension and re-install from the gallery.
