### ISSUE TITLE
Prepare release of V1.0.9

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#219]
Create an update of the Boost Test Adapter containing the following changes:
https://github.com/etas/vs-boost-unit-test-adapter/issues?utf8=✓&q=is%3Aclosed%20milestone%3Av1.0.9

**Comment by netspiri** [comment]
Version release notes available on netspiri [wiki](https://github.com/netspiri/vs-boost-unit-test-adapter/wiki/Version-History) fork. On approval, we will merge to the ETAS fork.

During ad-hoc testing, we identified some issues for which we have submitted pull requests. We would highly recommend that these are merged prior to release.

**Comment by guwirth** [comment]
@netspiri did a copy of the release nodes here:

### Version 1.0.9

Bug fixes:  
- Support file paths which utilise characters from system (native) encoding.
- Harden `--list_content=DOT` execution and react to process exit code.
- Improve test adapter reaction to exceptional cases and note errors as test failures.

Enhancements:
- Added Boost version identification.
- Added `One` test batch strategy (available as part of Boost.Test in Boost 1.63).
- Suppress blocking assertion message boxes for test execution.
- Added Boost 1.64, Boost 1.65 support.
- Removed dependency over the need of debug symbols (PDB files).
- Identify test adapter execution through `BUTA` environment variable.

Contributions/Special Thanks:
- @gastart - `BUTA` environment variable _red pill_
- @LukaszMendakiewicz - Boost 1.64, Boost 1.65 support

Pre-Requisites:
- [Boost Libraries](http://www.boost.org/users/download/). The following versions are supported:
  + Boost 1.60 and greater
- [Microsoft Visual Studio](https://www.visualstudio.com/). The following versions are supported:
  + Visual Studio 2015 (Community, Professional, Enterprise).

**Comment by guwirth** [comment]
@netspiri 

> During ad-hoc testing, we identified some issues for which we have submitted pull requests. We would highly recommend that these are merged prior to release.

Done: **1.0.9.45**

To the release notes: looks good, thx - would do two changes:
* first enhancements then bug fixes
* would add a note and link to the VS2017 version

**Comment by netspiri** [comment]
Updated as requested and merged to ETAS wiki
