### ISSUE TITLE
RFF Boost Unit Test Adapter 1.0.9.45 (RC1)

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#223]
Hi,

We are planning a new and last release of the Boost Unit Test Adapter for Visual Studio 2015 end of next week. Please try the linked version and give us feedback: [Download](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master/job/kufqkpn8c4ohu73h/artifacts)

### Version 1.0.9

Enhancements:
- Added Boost version identification.
- Added `One` test batch strategy (available as part of Boost.Test in Boost 1.63).
- Suppress blocking assertion message boxes for test execution.
- Added Boost 1.64, Boost 1.65 support.
- Removed dependency over the need of debug symbols (PDB files).
- Identify test adapter execution through `BUTA` environment variable.

Bug fixes:  
- Support file paths which utilise characters from system (native) encoding.
- Harden `--list_content=DOT` execution and react to process exit code.
- Improve test adapter reaction to exceptional cases and note errors as test failures.

Contributions/Special Thanks:
- @gastart - `BUTA` environment variable _red pill_
- @LukaszMendakiewicz - Boost 1.64, Boost 1.65 support

Pre-Requisites:
- [Boost Libraries](http://www.boost.org/users/download/). The following versions are supported:
  + Boost 1.60 and greater
- [Microsoft Visual Studio](https://www.visualstudio.com/). The following versions are supported:
  + Visual Studio 2015 (Community, Professional, Enterprise).

Note:
- [Test Adapter for Boost.Test](https://github.com/microsoft/vs-boost-unit-test-adapter) for Visual Studio 2017 is now available from the [Visual Studio Gallery](https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.TestAdapterforBoostTest) courtesy of Microsoft.

Regards,

**Comment by guwirth** [comment]
@ALL no feedback is good feedback.
@netspiri Everything ready to release?

**Comment by netspiri** [comment]
I don't think there is anything to add from our end. Hoping that all goes well.

**Comment by guwirth** [comment]
@all update done in Visual Studio Gallery
