### ISSUE TITLE
Discover dynamically linked BoostTest executables 

### ISSUE THREAD

**Issue by nickuhlenhuth** [etas/vs-boost-unit-test-adapter#224]
The adapter should use implicit association to identify dynamically linked boost test executables.
The Test Adapter for Google Test implemented it this way: https://github.com/Microsoft/TestAdapterForGoogleTest/commit/0318762acbd486b18947f0bbd0bffa202a33f8bf#diff-94449757f2b0ab3e5f5a7562b30017f0

**Comment by guwirth** [comment]
Hi @nickuhlenhuth,

Thanks a lot for the feedback. We are working currently on the final 1.0.9 release and will stop development in this repository after the release. I would like to ask you to move this issue to the Microsoft fork: https://github.com/Microsoft/vs-boost-unit-test-adapter.

Regards,
