### ISSUE TITLE
Use an optimized text search algorithm to find boost test keywords in source code

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#26]
Leftover of #21:
Wouldn't it be better to use an optimized text search algorithm (e.g see discussion here http://programmers.stackexchange.com/questions/183725/which-string-search-algorithm-is-actually-the-fastest) instead of using normal regular expressions or string search?

**Comment by netspiri** [comment]
We did some internal tests and implemented some of the mentioned algorithms in C#. Our benchmarks show that the String.Contains method is still faster than the custom algorithms or regular expressions for string searching.

Given the recent requests (#24), source code parsing should be made redundant for Boost Test 3 projects which should minimise the priority for this feature.

**Comment by guwirth** [comment]
Ok we close this
