### ISSUE TITLE
release notes/version number/documentation for release milestone v1.0.6.0

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#34]
In preparation for the release milestone v1.0.6.0, it is required

i) to update the version number to 1.0.6.0 in the plugin manifest
ii) to update the release notes and the version history wiki page
iii) to update any documentation (if required)

**Comment by guwirth** [comment]
Shifted to 1.0,7

**Comment by netspiri** [comment]
@guwirth Is it OK if we close this issue since it is directly related to 1.0.6? As far as the issue goes, the issue has been completed and merged. We can open a new one when the next version is about to release.
