### ISSUE TITLE
Update Documentation/Project Wiki

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#36]
Update the project documentation by adding further development topics of interest, mainly detailing development approach and project design philosophies. Topics which require additional documentation are:
- Home
  - Create a landing page for the Wiki. Should contain links to user related documentation and development related documentation.
- User Manual
  - Move manual over from Readme.md in order to have the readme file as minimalistic as possible.
- Visual Studio Test Platform Primer
  - Brief introduction to Visual Studio's Test Platform API's for newcomers.
- Boost Test Adapter Design Documentation
  - Brief overview of the design and structure of the test adapter, clarifying any assumptions in the process.
- Git Workflow
  - Detail pull-request submission procedure.
- Testing
  - Add sample Boost Test scenarios used for manual testing.

As a plus, images should be relatively linked to allow easier forking.

**Comment by netspiri** [comment]
Project Wiki updated. Refer to our [Wiki fork](https://github.com/netspiri/vs-boost-unit-test-adapter/wiki) for the mentioned updates.  
If update is OK, please merge https://github.com/netspiri/vs-boost-unit-test-adapter.wiki.git master branch to https://github.com/etas/vs-boost-unit-test-adapter.wiki.git master branch.

**Comment by guwirth** [comment]
Will do this as a last step before release.

**Comment by guwirth** [comment]
@netspiri this is done and can be closed?

**Comment by netspiri** [comment]
Wiki has been merged just recently. Issue can be safely closed.
