### ISSUE TITLE
Batch Test Runs 

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#37]
As requested by Paul Michalik [Each TEST_CASE runs in own process](https://visualstudiogallery.msdn.microsoft.com/5f4ae1bd-b769-410e-8238-fb30beda987f#18457), the option to batch test case runs should be made available. This is useful in scenarios where test fixture setup is to be avoided.

By design, a process is spawned per test case in order to have a responsive test adapter i.e. once a test completes, a single test can be immediately updated. The exception to the rule is code coverage were multiple tests are batched at test suite level to minimize symbol re-loading.

Test batching comes with a set of limitations:
- Timeouts on a test case level cannot be handled
- Memory leak detection has to be suppressed since it becomes difficult to distinguish leaks from specific tests

Ideally, an additional configuration element is added (e.g. ``<BatchTests>true</BatchTests>``) to the ``.runsettings`` configuration which defaults to ``false`` unless specified otherwise.

**Comment by guwirth** [comment]
How is this working internally? Comment on Visual Studio gallery: "It is important to understand that our plugin is only a wrapper on top of the boost test framework. First step is always to setup a test project with unit tests which results in a binary (exe = test runner). We call this exe and display the results with the help of a unit test adapter in VS. So it's mainly up to you how you distribute your tests to test projects. If you want to to run only one process you have to move all unit test into one test project."

**Comment by netspiri** [comment]
The mentioned comment is incorrect. The adapter will always spawn a dedicated process to execute a single test case. If 5 tests are available within a single test module (i.e. executable), 5 processes will be spawned, one after the other, each running a single test case at a time.

Test case execution isolation was a design decision in an attempt to make the test adapter responsive i.e. when a single test case is executed, the adapter is immediately updated with the test results of that particular test case. During development, this restriction was removed for code coverage scenarios in an attempt to avoid symbol reloading due to the many processes being created.

Will be updating the project Wiki with the design of the adapter to possibly minimise such inconsistencies in the future.

**Comment by netspiri** [comment]
Wiki updated with high-level [Boost Test Adapter Design](https://github.com/netspiri/vs-boost-unit-test-adapter/wiki/Boost-Test-Adapter-Design).
