### ISSUE TITLE
Sub folder exported projects

### ISSUE THREAD

**Issue by kanekotic** [etas/vs-boost-unit-test-adapter#4]
I am having problem with projects that are set into an internal folder and not the root one. 

If my output directory is the root folder it will not find the dll to be run, if the output folder is the sub folder the dependencies will not be loaded.

I don't know if this is something that can be solve from the runner side, or is just a singularity due my plugin architecture.

**Comment by netspiri** [comment]
Hello @kanekotic.  We are unable to understand and replicate the issues that you are having. Can you please generate and include in a reply, a bare-bones project(s) with the setup(s) that you are having issues with?

**Comment by kanekotic** [comment]
yep...no problem...I will do this when I am home

**Comment by kanekotic** [comment]
sorry for the late reply. i Basically troubleshoot this, it was caused in my case because during compilation i have a folder of plugins that will be registered in run-time. But they depend on parent folder compiled dlls. of course there is no linking on the run test phase. so i solved it by creating a test folder a robocopy all the dlls. It worked fine. If you guys have a more fashionable solution i am open to it. But i understand it is nothing caused by the adapter (or easily solvable for you).
