### ISSUE TITLE
Specify Test Execution Working Directory

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#43]
As described by [Roel_v](https://visualstudiogallery.msdn.microsoft.com/site/search?f%5B0%5D.Type=User&f%5B0%5D.Value=Roel_v)'s comment '[Set working directory](https://visualstudiogallery.msdn.microsoft.com/5f4ae1bd-b769-410e-8238-fb30beda987f#18625)', the working directory of test execution should be explicit and, ideally, defaults to the working directory as specified within a project's property sheets.

**Comment by netspiri** [comment]
One point to keep in mind regarding this issue is the possible difference in test environments. Currently, the test adapter does not assume it is running within a Visual Studio instance. Although unsupported at the moment, the Boost Test Adapter can run through [vstest.console.exe](https://msdn.microsoft.com/en-us/library/ms182486.aspx) and will be able to do so when the issue #24 is resolved. This allows the Boost Test Adapter to be used on continuous integration servers without the need of referring to additional properties.

It should be possible to test whether we are running in a Visual Studio instance but this will add the Visual Studio dependency in other components. Acquiring the _Working Directory_ property should be relatively easy to achieve. Resolving the content of the property i.e. elements such as $(ProjectDir) is another issue.

Recommended temporary workaround: Specify a post-build event which copies the necessary dependencies (shared libraries and resources) to a location which can be easily referenced by the test executable i.e. in test executable's output directory.

**Comment by netspiri** [comment]
Issue #4 may also be related to this.

**Comment by guwirth** [comment]
Why not set paths explicit inside unit tests or with fixture?
https://msdn.microsoft.com/en-us/library/windows/desktop/hh310513(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms686203(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/aa365530(v=vs.85).aspx
...

**Comment by netspiri** [comment]
The mentioned approach is valid but I would still consider it as a workaround. Ideally, we should strive to avoid having users modify the source code/project properties just to make use of the adapter.

**Comment by guwirth** [comment]
Setting working directory is fine, but in some cases approach above is needed, e.g.:

```C++
struct CDefineRootFolder {
    CDefineRootFolder() {
       ::AddDllDirectory("c:\\MyExtraDllFolder");
    }
    ~CDefineRootFolder() {
    }
};
BOOST_GLOBAL_FIXTURE(CDefineRootFolder);
```
