### ISSUE TITLE
Execute Tests Simultaneously

### ISSUE THREAD

**Issue by netspiri** [etas/vs-boost-unit-test-adapter#49]
Currently, the Boost Test Adapter spawns a process per test batch and these processes are later executed in sequence. In an attempt to execute tests faster, users should have the possibility to specify whether tests should be executed in parallel.

**Comment by guwirth** [comment]
Normally the sequence tests are executed are always random. So it should always be possible to execute them in parallel.

Starting with Boost 1.59 there is the **depends_on** keyword (http://www.boost.org/doc/libs/1_59_0/libs/test/doc/html/boost_test/utf_reference/test_org_reference/decorator_depends_on.html) to indicate a dependency.  A possible solution should support this.

**Comment by maschwie** [comment]
I think its not so much about "parallel", its rather about: 
TestRunnerProcess Spawning per. TestCase (selected in the VS Test Explorer) 

I opened a second issue "Configurable Test Runner Spawning" for that.

**Comment by netspiri** [comment]
Apparently Visual Studio 2015 Update 1 gave us this feature for free - http://blog.drorhelper.com/2015/12/vs2015-update-1-brings-back-parallel.html.

@guwirth Should we still make an effort and support older VS versions via a custom configuration property?

**Comment by guwirth** [comment]
@netspiri no would spend no extra effort here. Maybe we can document in the wiki how to activate and that feature needs vs2015 update 1 or later.
