### ISSUE TITLE
A few .log files missing from the BoostTestAdapterNunit project

### ISSUE THREAD

**Issue by mwu-tow** [etas/vs-boost-unit-test-adapter#5]
Hi,
first of all — congratulations on open-sourcing the project! Thank you for taking time to document the whole thing so well — it is really ease to see what's happening in the code.
I've always wanted to use this plugin for the tests in my project, however never got it to work — now I'll be able to debug and — perhaps — make the needed adjustments on my own :)

But, going to the matter:
it seems that several files are missing from the repository, causing the `BoostTestAdapterNunit` project to fail build. (and in case of removing references to that files, the 4 tests will fail because of that)
The missing files are:
* Resources\ReportsLogs\MemoryLeakTest\sample.NoSourceFileAndLineNumbersAvailable.test.stdout.log
* Resources\ReportsLogs\MemoryLeakTest\sample.SourceFileAndLineNumbersAvailable.test.stdout.log
* Resources\ReportsLogs\OutputTest\sample.test.stderr.log
* Resources\ReportsLogs\OutputTest\sample.test.stdout.log

Could you please check this and add them to the source control? Thanks!

**Comment by netspiri** [comment]
The missing log files are made available in merge request #7

**Comment by mwu-tow** [comment]
Thank you, with that merged I am able to properly build the whole solution and run all the nunit tests. :)
A few ones are failing, probably due to git messing with line endings, but that's another topic.

**Comment by netspiri** [comment]
@mwu-tow I just [restored](https://github.com/etas/vs-boost-unit-test-adapter/commit/39a335b76e1e95a7d08b91cd3cbfb8a8cba61fbe) SingleLineCommentFilterTest_FilteredSourceCode.cpp which I suspect is the file that was causing one of the unit tests to fail as per your last comment.  I also added a .gitattributes so as to disable the CRLF behaviour of Git.

**Comment by mwu-tow** [comment]
Yes, that fixed two of the tests. Remaining failing ones are `MemoryLeakSourceFileAndLineNumbersAvailable` and `MemoryLeakNoSourceFileAndLineNumbersAvailable`. Is this a known problem or should I open a new issue report and provide more details?

**Comment by netspiri** [comment]
I just downloaded anew your fork and my fork.  I merged in, the five files that I committed this morning (apart from the .gitattributes) to your fork, compiled and ran the tests.  All the 120 pass just fine.

I suggest that you do open another ticket so as that we track this issue.  The only detail that is required at this point is the name of the tests (and optionally the reason of the test failure).  I would then suggest to wait for the repo owners to accept the current pull/merge requests.  I will then rebuild and run the unit tests again....and then I'll trigger you to retest again.  Is this ok for you?

**Comment by mwu-tow** [comment]
Yes, absolutely. I'll get to this tomorrow.
Thank you for all your help. :)

**Comment by mwu-tow** [comment]
Hi merged all your pull requests and made a new clean clone. Now all the 120 tests are passing fine. Sorry for the false alarm, something must have went off before. (perhaps the line endings change didn't affect the previously checked out files)
So this issue can be resolved as soon as #7 goes through.

**Comment by netspiri** [comment]
Hello mwu-tow. Ok, thanks for letting us know. Have a nice weekend.

**Comment by guwirth** [comment]
@mwu-tow Can we close this?

**Comment by mwu-tow** [comment]
Yes, of course.
