### ISSUE TITLE
Add Unit Test execution to AppVeyor

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#50]
Currently AppVeyor is used for build verification only. Should also execute unit tests after a successful build: http://www.appveyor.com/docs/running-tests. 

As a contributor to BUTA I'm able to see if my changes provided by a PR are passing the existing unit tests.

**Comment by guwirth** [comment]
Saw it is already working. Will add link to test results tomorrow to readme.md.

**Comment by netspiri** [comment]
Unit tests are already being executed per build configuration.

Currently there is no direct support for unit test badges from AppVeyor but there are alternatives available such as the [TestStatusBadge](https://github.com/mmaitre314/TestStatusBadge) project.

Using this project, the markdown code for the adapter test status badge would be of the form:

`[![Test status](http://teststatusbadge.azurewebsites.net/api/status/guwirth/vs-boost-unit-test-adapter)](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter)`

[![Test status](http://teststatusbadge.azurewebsites.net/api/status/guwirth/vs-boost-unit-test-adapter)](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter)
