### ISSUE TITLE
V1.0.6 release

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#52]
Hi, whats open for V1.0.6 release? Can we start with final testing?

**Comment by guwirth** [comment]
Decision is to release 1.0.6 with bug fixes only, features will be moved to 1.0.7. Especially #64 is more effort because of the DOT file parsing.

**Comment by netspiri** [comment]
Issues #23 and #24 which are related to ``--list_content`` have to be reopened and expected for milestone 1.0.7.0.

Issue #34 also needs to be reopened given recent decisions. Release notes will need to reflect expected changes.

**Comment by guwirth** [comment]
Update of version history: https://github.com/etas/vs-boost-unit-test-adapter/wiki/Version-History

**Comment by netspiri** [comment]
Wiki updated with latest release notes.

**Comment by guwirth** [comment]
@netspiri ready to release V1.0.6?

**Comment by netspiri** [comment]
Currently doing some ad-hoc testing on latest build. Will update status accordingly.

**Comment by guwirth** [comment]
Did a test with Win7 64bit, VS2015 Update 1, latest BUTA 1.0.6.15 and Boost 1.59: :+1:

**Comment by netspiri** [comment]
Did some small tests over the past days using VS2015, VS2012 using Boost 1.59 and Boost 1.49 during our general workflow. Seems to operate as expected.

**Comment by guwirth** [comment]
From my side we can release it :+1:

**Comment by paumayr** [comment]
Can we have a 1.0.6 release ? :) I'm hanging on #79 .

**Comment by netspiri** [comment]
:+1:

**Comment by guwirth** [comment]
In case of blocking issues for boost test 1.60 we should release a new version in the Visual Studio Gallery and shift other points to 1.0.7.

@netspiri could you prepare everything for a release please (or is all already up to date)?

**Comment by netspiri** [comment]
@guwirth PR #83 contains a minor update to the release notes describing the Boost 1.60 fix contributed by @sergegers. Wiki has also been recently updated and internal tests show promise.

Our recommendation is to merge the last PR, tag the latest commit and AppVeyor *should* produce a build version-ed as 1.0.6.0 (tagged commits should have the build number reset to 0). The release artifact generated by AppVeyor should suffice for release purposes.

**Comment by guwirth** [comment]
@netspiri 
*  merge #83: done
* AppVeyor should produce a build version-ed as 1.0.6.0: not a good idea. version number must be always unique. Fourth digit doesn't matter. If we wanna do this we should add something like x.x.x.x-SNAPSHOT in feature. Then we can remove it later one. But would keep the way we are doing it currently with increasing build number.

**Comment by netspiri** [comment]
@guwirth We automated the process listed in the 'Versioning and Building' section of the [Building from Source](https://github.com/etas/vs-boost-unit-test-adapter/wiki/Building) article in the Wiki. If you think that this is not suitable, please open a new issue detailing what is expected.

P.S. AppVeyor still auto-increments the build number on each commit. Only tagged commits have their build number set to 0 but it is expected that either the major, minor or revision number (or a combination thereof) is manually updated in the [vsixmanifest](https://github.com/etas/vs-boost-unit-test-adapter/blob/master/BoostTestPlugin/source.extension.vsixmanifest) before tagging the release commit.

**Comment by guwirth** [comment]
@netspiri I think we misunderstood each other.
* I like to keep it as today
* I would never reset version numbers. Its no problem to release a 1.0.6.17

**Comment by paumayr** [comment]
FYI: I've installed 1.0.6.17 and it resolved the issues I had with boost 1.60. Cheers!

**Comment by candychiu** [comment]
How do I get 1.0.6.17?

**Comment by paumayr** [comment]
Don't want to spoil the release for the team, but I got it from appveyor. 
Here: https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter

**Comment by netspiri** [comment]
Hi @candychiu,

As correctly pointed out by @paumayr, the release version of 1.0.6.17 is available at https://ci.appveyor.com/api/buildjobs/hargs052rmaldy2d/artifacts/BoostTestPlugin/bin/Release/BoostUnitTestAdapter.vsix.

Please note that this is still an in-development build and not a public release. I'll update documentation regarding this point.

**Comment by netspiri** [comment]
@guwirth PR #84 should fix the mentioned issue. 'Versioning and Building' section of the [Building from Source](https://github.com/etas/vs-boost-unit-test-adapter/wiki/Building) article in the Wiki was also updated to reflect recent discussions.

@candychiu Wiki updated on how to download in-development builds. Please refer to 'Download a Development Build' section from the [Continuous Integration](https://github.com/etas/vs-boost-unit-test-adapter/wiki/Continuous-Integration-AppVeyor) article.

**Comment by guwirth** [comment]
@netspiri V1.0.6.19 ready to release in Visual Studio Gallery?

**Comment by netspiri** [comment]
:+1:

**Comment by guwirth** [comment]
Latest version V1.0.6.20 (+1 because of tagging) is available in Visual Studio Gallery now

**Comment by sergegers** [comment]
@guwirth :100:
