### ISSUE TITLE
The project environment is not set to run tests

### ISSUE THREAD

**Issue by starlight-point** [etas/vs-boost-unit-test-adapter#71]
The corresponding environment is not set to run the exe-file with tests in current configuration (configured in the "Configuration Properties - Debugging - Environment"). The executable file can not be launched without correct release/debug environment (PATH replacement).

**Comment by guwirth** [comment]
Duplicate #43 ?

**Comment by starlight-point** [comment]
Partly duplicates, I was more interested in creating a suitable environment (not only working dir) for running applications for debugging and testing. `AddDllDirectory` does not work because the libraries are used by exe-loader, not at runtime. All IDEs and continuous integration tools support environment configuration, I would not like to create a soft-links specially for a plugin.

Hard-linking or copying (if hard-link is not allowed) for packaging occurs on the next step after a successful execution of the tests.

I tried to replace the "Debugging Command / Command Arguments" in project settings to `$(SolutionDir)runtests.cmd` (which configures the environment) and `$(TargetPath)` as the arugment, but plugin ignores them. Configuration of `<ExternalTestRunner type=".exe">` is not suitable because I do not have custom `<DiscoveryCommandLine>`.

**Comment by guwirth** [comment]
@starlight-point could you make a concrete proposal please.
* How should it work?
* What exactly should be supported?

**Comment by starlight-point** [comment]
I would like to see:
* Setting environment variables before running tests according to the project `Environment` configuration that contains test(s) - [example image](http://stackoverflow.com/questions/100543/how-do-i-set-specific-environment-variables-when-debugging-in-visual-studio).
* Launch another executable file with additional arguments, according to the parameters `Command` and` Command Arguments` in project configuration (optionally).
* You can also take into account `Working Directrory` for #43.

**Comment by guwirth** [comment]
closed with #99
