### ISSUE TITLE
Test discovery is very slow due to filtering raw string literals 

### ISSUE THREAD

**Issue by mwu-tow** [etas/vs-boost-unit-test-adapter#8]
Hi,
I have a relatively big c++ project (about 15 MB of code). The test discovery takes about 30 minutes. That makes the adapter hardly usable. 

Practically all that time is spend in the Regex Replace method calls from a single line:
https://github.com/etas/vs-boost-unit-test-adapter/blob/master/BoostTestAdapter/SourceFilter/QuotedStringsFilter.cs#L75
```c#
cppSourceFile.SourceCode = stringLiteralsRegex.Replace(cppSourceFile.SourceCode, new MatchEvaluator(ComputeReplacement));
```

If I comment out this single line, the discovery time on my project goes down from 29 minutes to 1 second. The stringLiteralsRegex seems to be really costly to use.

**Comment by netspiri** [comment]
Very interesting find.  I'll try to find a more efficient way to do it.

How did you actually identify that that line number was giving you such a performance hit?  Did you actually profile it or did you utilize the new elapsed feature from vs2015 as described [here](http://blogs.msdn.com/b/visualstudioalm/archive/2015/07/20/performance-and-diagnostic-tools-in-visual-studio-2015.aspx)?

**Comment by mwu-tow** [comment]
At first I put some logs to measure time for future reference. Then I have used the profiler so see how that time is actually spent. 
The elapsed time feature wouldn't be of much help here, since stepping over the only significant line takes half an hour. I am not patient enough. ;-) However, the feature itself certainly has its merits.
